config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :scribbles

  resources :users do
    resources :scribbles
  end

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"
  resources :scribbles 
  root :to => "scribbles#index"

  get '/posts/history', to: 'posts#history', as: :posts_history
  resources :posts

end

app/models/scribble.rb
class Scribble < ActiveRecord::Base
  
  belongs_to :user
  has_paper_trail


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :scribbles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  
  #before_action :authenticate_user!
  #protect_from_forgery with: :exception

  # Verify that controller actions are authorized. Optional.
  # after_filter :verify_authorized,  except: :index
  # after_filter :verify_policy_scoped, only: :index
 

  # Globally rescue Authorization Errors in controller.
  # Returning 403 Forbidden if permission is denied
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
 
  # Enforces access right checks for individuals resources
  #after_filter :verify_authorized, :except => :index
 
  # Enforces access right checks for collections
  #after_filter :verify_policy_scoped, :only => :index
 
 
  private


  def user_not_authorized
    flash[:error] = "You are not authorized to view or edit this"
    redirect_to root_path
  end

end

app/controllers/scribbles_controller.rb
class ScribblesController < ApplicationController

  #before_action :set_scribble, only: [:show, :edit, :update, :destroy]

  # GET /scribbles
  # GET /scribbles.json
  def index
    @scribbles = Scribble.all
    #show posts from current user OR posts that are shared with the current user
    #@scribbles = current_user.scribbles 

  end

  def shared_with
    #read shared_with from scribble, turn array of users, lookup in usertable
  end

  # GET /scribbles/1
  # GET /scribbles/1.json
  def show
     @scribble = Scribble.find(params[:id])
     authorize @scribble
     @versions = PaperTrail::Version.order('created_at DESC')
  end

  # GET /scribbles/new
  def new
    @scribble = Scribble.new
  end


  # GET /scribbles/1/edit
  def edit
     @scribble = Scribble.find(params[:id])
     authorize @scribble
  end

  # POST /scribbles
  # POST /scribbles.json
  def create
    @scribble = Scribble.new(scribble_params)
    
    #link scribble to user
    @scribble.user_id = current_user.id
    @scribble.created = DateTime.now
    respond_to do |format|
      if @scribble.save
        format.html { redirect_to @scribble, notice: 'Scribble was successfully created.' }
        format.json { render :show, status: :created, location: @scribble }
      else
        format.html { render :new }
        format.json { render json: @scribble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scribbles/1
  # PATCH/PUT /scribbles/1.json
  
  def update
    @scribble = Scribble.find(params[:id])
    respond_to do |format|
      if @scribble.update(scribble_params)
        format.html { redirect_to @scribble, notice: 'Scribble was successfully updated.' }
        format.json { render :show, status: :ok, location: @scribble }
      else
        format.html { render :edit }
        format.json { render json: @scribble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scribbles/1
  # DELETE /scribbles/1.json
  def destroy
    @scribble.destroy
    respond_to do |format|
      format.html { redirect_to scribbles_url, notice: 'Scribble was successfully deleted. #{undo_link}' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scribble
      @scribble = Scribble.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scribble_params
      params.require(:scribble).permit(:title, :tags, :content, :created, :published)
    end
      
    def undo_link  
      view_context.link_to("undo",
        revert_version_path(@scribble.versions.scoped.last),
        :method => :post)
    end

    # paper_trail history method
    def history
      @versions = PaperTrail::Version.order('created_at DESC')
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scribbles_helper.rb
module ScribblesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title
      | Starter Template for Bootstrap
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    meta name="description" content=""
    meta name="author" content=""
    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-collapse"
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Scribbles", "/scribbles", :class => "navbar-brand"
        .collapse.navbar-collapse
          ul.nav.navbar-nav
            li.active
              a href="#"
                | Home
            li
              a href="#about" 
                | About
          / FS 140716: added login status to navbar
          p.navbar-text.pull-right
            - if user_signed_in?
              strong
              = link_to current_user.email, edit_user_registration_path, :class => 'navbar-link'
              |  | 
              = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
            - else
              = link_to "Sign in", new_user_session_path, :class => 'navbar-link'
              |  | 
              = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do
          button.close type="button" data-dismiss="alert" aria-hidden="true"
            | &times;
          = msg
      = yield

app/views/scribbles/_form.html.slim
= form_for(@scribble, :html => { :class => "form-horizontal" }) do |f|
  - if @scribble.errors.any?
    .alert.alert-danger.alert-dismissable
      button.close type="button" data-dismiss="alert" aria-hidden="true" 
        | &times;
      h4= "#{pluralize(@scribble.errors.count,"error")} prohibited this scribble from being saved:"
      ul
        - @scribble.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :title, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :title, :class => "form-control"
  .form-group
    = f.label :tags, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :tags, :class => "form-control"
  .form-group
    = f.label :content, :class => "col-sm-2 control-label"
    .col-sm-10
      #epiceditor
        = f.text_area :content, :class => "form-control", :style => "height:275px"  
  .form-group
    = f.label :created, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.date_select :created, :class => "form-control"
  .form-group
    = f.label :published, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.check_box :published, :class => "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => "btn btn-primary"

app/views/scribbles/edit.html.slim
.page-header
  = link_to scribbles_path, :class => 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @scribble, :class => 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | scribble

= render 'form'

app/views/scribbles/index.html.slim
.page-header
  = link_to new_scribble_path, :class => 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Scribble
  h1
    | Listing scribbles

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | User
        th
          | Title
        th
          | Tags
        th
          | Created
        th
        th
    tbody
      - @scribbles.each do | scribble |
        tr
          td
            = scribble.user_id
          td
            = link_to scribble.title, scribble
          td
            = scribble.tags
          td 
            = scribble.created
          td 
            = link_to 'Edit', edit_scribble_path(scribble), :class => "btn btn-primary"
          td 
            = link_to 'Delete', scribble, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary" 

app/views/scribbles/new.html.slim
.page-header
  = link_to scribbles_path, :class => 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | scribble

= form_for(@scribble, :html => { :class => "form-horizontal" }) do |f|
  - if @scribble.errors.any?
    .alert.alert-danger.alert-dismissable
      button.close type="button" data-dismiss="alert" aria-hidden="true" 
        | &times;
      h4= "#{pluralize(@scribble.errors.count,"error")} prohibited this scribble from being saved:"
      ul
        - @scribble.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :title, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :title, :class => "form-control"
  .form-group
    = f.label :shared_with, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :shared_with, :class => "form-control"
  .form-group
    = f.label :tags, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :tags, :class => "form-control"
  .form-group
    = f.label :content, :class => "col-sm-2 control-label"
    .col-sm-10
      #epiceditor
	    = f.text_area :content, :class => "form-control", :style => "height:275px" 

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => "btn btn-primary"

app/views/scribbles/show.html.slim
.page-header
  = link_to scribbles_path, :class => 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_scribble_path(@scribble), :class => 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show scribble
dl.dl-horizontal
  dt
    | User:
  dd
    = @scribble.user_id
  dt
    | Title:
  dd
    = @scribble.title
  dt
    | Shared with:
  dd
    = @scribble.shared_with
  dt
    | Tags:
  dd
    = @scribble.tags
  dt
    | Content:
  dd
    = @scribble.content
  dt
    | Created:
  dd
    = @scribble.created
  dt
    | Published:
  dd
    = @scribble.published


  h1 
    | versions
dl.dl-horizontal
  ul
    - @versions.each do |version|
      li
        = l(version.created_at, format: "%-d.%m.%Y %H:%M:%S %Z")
        br/
        | Event ID: #{version.id}

        br/
        div
          | More info:
          pre= version.object